### ISSUE TITLE
Getting the bloody thing to work

### ISSUE THREAD

**Issue by tg359** [FraserGreenroyd/SAMAzure#9]
- [x] Upload files to blob container and get ID information
- [x] Generate pool with startup commands
- [x] Check pool-node works with CLI
- [x] Create job (scalable past 100 tasks)
- [x] Add tasks to job (more jobs if > 100 tasks)
- [x] Add scalability to pool
- [x] Run job/s and output results into container
- [x] Download stored results from blob to local

**Comment by FraserGreenroyd** [comment]
For some reason this isn't closed despite the PR being closed and merged in so closing now.
